/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBAlert.h"

@interface SBVoiceControlAlert : SBAlert
{
    struct {
        unsigned int shouldBeActivated:1;
        unsigned int isReadyToBeActivated:1;
        unsigned int hasBeenActivated:1;
    } _voiceControlFlags;
}

+ (id)pendingOrActiveAlert;
+ (void)registerForAlerts;
+ (void)unregisterForAlerts;
+ (BOOL)shouldEnterVoiceControl;
+ (BOOL)resetVoiceControlIfNecessary:(BOOL)arg1;
+ (void)bluetoothDeviceRequestedVoiceControl:(id)arg1;
+ (void)bluetoothDeviceTerminatedVoiceControl:(id)arg1;
+ (BOOL)_bluetoothDevicesPickable;
+ (void)_configureSession:(id)arg1 forAlert:(id)arg2;
+ (void)setNextRecognitionAudioInputPaths:(id)arg1;
+ (void)_setNextRecognitionAudioInputPathForSession:(id)arg1 resetting:(BOOL)arg2;
- (void)_resign;
- (void)_makeActive;
- (id)_session;
- (void)_workspaceActivate;
- (BOOL)recognitionSessionWillBeginAction:(id)arg1;
- (void)_prime;
- (void)_setRoutingAttributesForWiredHeadset:(BOOL)arg1;
- (id)init;
- (id)initFromWiredHeadsetButton;
- (id)initFromBluetoothDevice:(id)arg1;
- (BOOL)allowsEventOnlySuspension;
- (void)deactivate;
- (void)deactivateAfterLocking;
- (void)activate;
- (id)initFromMenuButton;
- (void)activateWhenReady;
- (void)cancelIfNotActivated;
- (void)cancel;
- (void)dealloc;
- (void)_proximityChanged:(id)arg1;
- (void)handleHeadsetButtonUpFromActivation:(BOOL)arg1;
- (BOOL)handleMenuButtonTap;
- (double)autoDimTime;
- (id)alertDisplayViewWithSize:(struct CGSize)arg1;

@end

