/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "SBSlidingAlertDisplay.h"

#import "VSRecognitionSessionDelegate-Protocol.h"
#import "VSSpeechSynthesizerDelegate-Protocol.h"

@class AVController, NSDictionary, NSInvocation, NSMutableArray, NSMutableIndexSet, NSMutableSet, NSTimer, UITextField, UIView, VSRecognitionSession;

@interface SBVoiceControlAlertDisplay : SBSlidingAlertDisplay <VSRecognitionSessionDelegate, VSSpeechSynthesizerDelegate>
{
    VSRecognitionSession *_session;
    BOOL _wasRecognizing;
    BOOL _didConfigureRouting;
    NSInvocation *_postSoundInvocation;
    UIView *_leftFadeView;
    UIView *_rightFadeView;
    UIView *_labelsView;
    int _clipCount;
    int _currentClipNo;
    BOOL _voiceTranscription;
    UITextField *_textField;
    NSMutableArray *_transcripts;
    NSMutableArray *_voiceClips;
    AVController *_avController;
    NSMutableArray *_waves;
    NSMutableSet *_labels;
    int _keywordCount;
    int _lastKeywordIndex;
    NSTimer *_levelTimer;
    NSMutableIndexSet *_occupiedLabelSlots;
    NSDictionary *_locStrings;
    BOOL _labelsOn;
    BOOL _animatingToCall;
    BOOL _didDismiss;
    BOOL _awaitingButtonRelease;
    BOOL _isBecomingVisible;
    BOOL _labelsHaveDisplayed;
}

+ (id)newBottomLockBarForDisplay:(id)arg1;
+ (id)newBottomBarForInstance:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 session:(id)arg2;
- (BOOL)_wasTriggeredByMenu;
- (void)updateDesktopImage:(id)arg1;
- (void)dealloc;
- (BOOL)alphanumericKeyboard;
- (id)_localizedStringForKey:(id)arg1;
- (void)setTitleText:(id)arg1;
- (void)setStatusText:(id)arg1;
- (void)alertDisplayWillBecomeVisible;
- (void)alertWillBeDismissed;
- (void)lockBarUnlocked:(id)arg1;
- (void)setMiddleContentAlpha:(float)arg1;
- (void)_invalidateRouting;
- (void)_notifyDeviceTermination;
- (void)_dismissIfWeHavent;
- (void)_dismissSlightlyLater;
- (void)handleButtonUpCancel;
- (void)handleHeadsetButtonUpFromActivation:(BOOL)arg1;
- (id)_desiredRouteDictionary;
- (void)_pickedRouteChanged:(id)arg1;
- (void)_configureRoutingIfNecessary;
- (void)_performSoundCompletionAction;
- (BOOL)_attemptPlaySound:(unsigned long)arg1 synchronously:(BOOL)arg2;
- (void)_playSound:(unsigned long)arg1 synchronously:(BOOL)arg2;
- (void)_startSession;
- (void)_resetSession;
- (BOOL)recognitionSessionWillBeginAction:(id)arg1;
- (void)_continueRecognitionAction;
- (void)recognitionSessionDidBeginAction:(id)arg1;
- (void)_performNoMatchFound;
- (void)_promptUserForVoiceTranscription;
- (void)_mediaPlayerDied;
- (void)_userEnteredTextForVoiceClip:(id)arg1;
- (void)_startTrancribeAudio;
- (void)_getAudioClipsFromDirectory;
- (void)_playAudioAtPath:(id)arg1;
- (void)_exitVoiceTranscriptView;
- (void)recognitionSession:(id)arg1 didCompleteActionWithError:(id)arg2;
- (void)_finishedFadingToAwayInCallController;
- (void)_animateToAwayInCallController;
- (id)_openTelURL:(id)arg1;
- (id)_openVideoURL:(id)arg1;
- (id)recognitionSession:(id)arg1 openURL:(id)arg2;
- (void)_continueWithRecognitionAction;
- (void)_performConfirmationAction;
- (void)_speakFeedbackText;
- (void)_speakText:(id)arg1;
- (void)recognitionSession:(id)arg1 didFinishSpeakingFeedbackStringWithError:(id)arg2;
- (void)_updateLevels;
- (void)_startUpdatingLevels;
- (void)_stopUpdatingLevels;
- (void)_setWaveAlpha:(float)arg1 withDuration:(double)arg2;
- (int)_keywordCount;
- (void)_startLabelForKeywordAtIndex:(int)arg1 now:(BOOL)arg2 delayStart:(BOOL)arg3;
- (void)_startKeywordIfNecessary;
- (void)_labelFinishedAnimating:(id)arg1 finished:(id)arg2 label:(id)arg3;
- (void)_startMovingLabels;
- (void)_fadeOutCurrentLabels;
- (void)_stopMovingLabels;
- (void)_keywordsChanged:(id)arg1;

@end

