/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@class NSRecursiveLock, NSString;

@interface SBWiFiManager : NSObject
{
    NSRecursiveLock *_lock;
    struct __WiFiManagerClient *_manager;
    struct __WiFiDeviceClient *_device;
    NSString *_deviceInterfaceName;
    struct __WiFiNetwork *_currentNetwork;
    struct __WiFiNetwork *_previousNetwork;
    BOOL _currentNetworkHasBeenSet;
    BOOL _currentNetworkIsIOSHotspot;
    BOOL _currentNetworkIsIOSHotspotHasBeenSet;
    BOOL _powered;
    BOOL _poweredHasBeenSet;
    int _rssiThreshold;
    int _signalStrengthBars;
    int _signalStrengthRSSI;
    BOOL _signalStrengthHasBeenSet;
    BOOL _canPollSignalStrength;
    struct __SCDynamicStore *_SCDynamicStoreNetworkState;
    struct dispatch_source_s *_SCUpdateTimeoutSource;
    struct __WiFiNetwork *_primaryInterface;
    BOOL _primaryInterfaceHasBeenSet;
    BOOL _isPrimaryInterface;
    BOOL _isPrimaryInterfaceChanging;
    double _lastSignalStrengthUpdateTime;
    struct dispatch_source_s *_signalStrengthTimerSource;
}

+ (id)sharedInstance;
- (id)init;
- (struct __WiFiManagerClient *)_manager;
- (void)_updateWiFiState;
- (void)_powerStateDidChange;
- (void)_linkDidChange;
- (void)_updateWiFiDevice:(id)arg1;
- (void)_updateCurrentNetwork;
- (BOOL)isAssociated;
- (BOOL)isAssociatedToIOSHotspot;
- (BOOL)_cachedIsAssociated;
- (id)currentNetworkName;
- (BOOL)isPowered;
- (BOOL)wiFiEnabled;
- (void)setWiFiEnabled:(BOOL)arg1;
- (int)signalStrengthBars;
- (int)signalStrengthRSSI;
- (void)updateSignalStrength;
- (void)_updateSignalStrengthTimer;
- (id)knownNetworks;
- (void)resetSettings;
- (BOOL)isPrimaryInterface;
- (id)_wifiInterface;
- (void)_primaryInterfaceChanged:(BOOL)arg1;

@end

